name: Build

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'


jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }} for Python ${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            python: "3.11"
            cp: "cp311"
          - os: ubuntu-latest
            python: "3.12"
            cp: "cp312"
          - os: ubuntu-latest
            python: "3.13"
            cp: "cp313"
          - os: windows-latest
            python: "3.11"
            cp: "cp311"
          - os: windows-latest
            python: "3.12"
            cp: "cp312"
          - os: windows-latest
            python: "3.13"
            cp: "cp313"
          # - os: macos-latest
          #   python: "3.11"
          #   cp: "cp311"
          # - os: macos-latest
          #   python: "3.12"
          #   cp: "cp312"
          # - os: macos-latest
          #   python: "3.13"
          #   cp: "cp313"

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.0.1
        env:
          CIBW_BUILD: ${{ matrix.cp }}-*
          CIBW_SKIP: "*-musllinux*"
        with:
          output-dir: wheelhouse

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-py${{ matrix.python }}
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution (sdist)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install maturin
        run: pip install maturin

      - name: Build sdist with maturin
        run: maturin sdist

      - uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: ./target/wheels/*.tar.gz